### ISSUE TITLE
Study plan CRUD

### ISSUE THREAD

**Issue by pedrolunatech** [lunatech-labs/lunatech-competence-center-online#147]
Replace confluence has the center for study plans. Add study plans data and management functionality to this app.

Create 4 backend API endpoints: 
- POST for adding a study plan for a student
- PUT for updating a study plan for a student
- DELETE for inactivating a study plan for a student
- GET for getting a list of study plan based on filter fields

Create frontend for view and actions associated.

**Comment by smthelusive** [comment]
https://github.com/lunatech-labs/lunatech-competence-center-online/pull/176
