### ISSUE TITLE
Tech matrix: how to update his skills?

### ISSUE THREAD

**Issue by pepite** [lunatech-labs/lunatech-competence-center-online#168]
I fills in some skills but would like to update some. How do I do that ? The + button disappeared....

**Comment by smthelusive** [comment]
you can go to **menu -> your profile** and update on this page

**Comment by pepite** [comment]
I don't see a My profile: 

<img width="485" alt="screenshot 2018-08-30 at 23 11 11" src="https://user-images.githubusercontent.com/180989/44879491-17e37300-acaa-11e8-8f13-39fb97e15ab8.png">

I can only see search profile and then I cannot click on my own profile:

<img width="1084" alt="screenshot 2018-08-30 at 23 11 33" src="https://user-images.githubusercontent.com/180989/44879516-27fb5280-acaa-11e8-8a1b-dab7a9ac59e9.png">

**Comment by smthelusive** [comment]
try this link: http://techmatrix.lunatech.com/#!/user/home

**Comment by smthelusive** [comment]
btw looks like this and some similar issues should be on this [project](https://github.com/lunatech-labs/lunatech-tech-matrix/issues) :)

**Comment by pepite** [comment]
The url works. Creating another issue in the other project.
