### ISSUE TITLE
update to polymer2

### ISSUE THREAD

**Issue by erikwj** [lunatech-labs/lunatech-competence-center-online#65]
Probably best to do as soon as possible to make it less painful

**Comment by erikwj** [comment]
https://vaadin.com/elements/-/element/vaadin-grid#demos as an alternative for the datatable that currently only supports polymer 1

**Comment by eamelink** [comment]
I think we should do this, as soon as we've fixed #73

**Comment by eamelink** [comment]
Merge request is ready: https://github.com/lunatech-labs/lunatech-competence-center-online/pull/95

**Comment by eamelink** [comment]
Done
