### ISSUE TITLE
Link to polymer components

### ISSUE THREAD

**Issue by erikwj** [lunatech-labs/lunatech-competence-center-online#66]
The polymer components should be standalone components in the repository and can be worked on separately. These should be linked in the generic CCO project

**Comment by eamelink** [comment]
This is related to #55 

The main task for this (#66) issue, is how can we depend on bower components on the filesystem. Potentially this gives some ideas: http://bowerstatic.readthedocs.io/en/latest/local.html

It might be that we conclude that this is too much of a mine field and we should just put the polymer components into the `frontend` directory tree.

**Comment by ag91** [comment]
Are not we doing this for cv-editor already? The bit of the [README](https://github.com/lunatech-labs/lunatech-competence-center-online/tree/master/frontend) that goes `Next run bower link cv-editor && bower install in folder frontend.
` seems to be making available in the bower dependencies a component developed locally.

Am I misunderstanding the issue?

**Comment by eamelink** [comment]
An `npm install` in the frontend directory now links the frontend components.
